# Generated by Django 3.1 on 2020-08-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0002_auto_20200810_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question_type', models.CharField(choices=[('boolean', 'Boolean'), ('only_one', 'Only one answer is correct'), ('more_than_one', 'More than one answer is correct'), ('more_than_one_all_must_correctly', 'More than one answer is correct and all of them must be answered correctly')], max_length=50)),
                ('choises', models.CharField(choices=[('boolean', 'Boolean'), ('only_one', 'Only one answer is correct'), ('more_than_one', 'More than one answer is correct'), ('more_than_one_all_must_correctly', 'More than one answer is correct and all of them must be answered correctly')], max_length=50)),
                ('correct_answer', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('correct', models.BooleanField()),
                ('score', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
        ),
    ]
