# Generated by Django 3.1 on 2020-08-12 19:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200810_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='posible_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[''], size=3),
            preserve_default=False,
        ),
    ]
